### PR TITLE
fix: support spaces as sperator for vendor-option graphic-margin

### LINKED ISSUE #987: GeoServer `<sld:VendorOptions name="graphic-margin" />` handling is unstable
# Bug

**Describe the bug**
The in #971 introduced support for GeoServer `<sld:VendorOptions name="graphic-margin" />` tags, does not handle all supported format definitions of the `graphic-margin` property.

Currently the parser expects multiple margins to be separated by comma. As stated in [this](https://docs.geoserver.org/main/en/user/styling/sld/extensions/margins.html) GeoServer guide, multiple margins can be separated by space.

**To Reproduce**
1.Use https://github.com/geostyler/geostyler-sld-parser/blob/main/data/slds/geoserver/pattern_polygon.sld
1. Change all commas for `<sld:VendorOptions name="graphic-margin" />` to spaces
1. `Symbolizer#graphicFillPadding` is an array of `NaN`.

**Expected behavior**
 `<sld:VendorOptions name="graphic-margin" />` tags with multiple margins separated by space should be supported.

**Screenshots**
-
**Desktop (please complete the following information):**
-

**Smartphone (please complete the following information):**
-

**Additional context**
-

If desired I am happy, to provide a PR to fix this bug.

### PR DESCRIPTION
**Pull request by sebastianfrey**
Closes #987

### CODE REVIEW

File: src/SldStyleParser.ts [hunk 1]
```diff
@@ -1001,7 +1001,7 @@ export class SldStyleParser implements StyleParser<string> {
     if (this.withGeoServerVendorOption) {
       const graphicFillPadding = getVendorOptionValue(sldSymbolizer, 'graphic-margin');
       if (!isNil(graphicFillPadding)) {
-        fillSymbolizer.graphicFillPadding = graphicFillPadding.split(',').map(numberExpression);
+        fillSymbolizer.graphicFillPadding = graphicFillPadding.split(/[,\s]/).map(numberExpression);
```
Comment (jansule) [inline src/SldStyleParser.ts:1004]: Great catch @sebastianfrey! Turns out GeoServer actually expects only spaces and no commas (validating the style does not show any errors, applying it however does). Could you adjust this accordingly?

**Review by jansule — CHANGES_REQUESTED** [review]

File: src/SldStyleParser.ts (hunk 1 above)
Comment (sebastianfrey) [reply src/SldStyleParser.ts:1004]: @jansule Adopted the write path for the `graphic-margin` prop. Is this the change you were looking for?

**Review by jansule — APPROVED** [review]
Yes, perfect! Thanks for addressing the remarks @sebastianfrey

**Comment by ger-benjamin** [comment]
Waouh, thanks,I come across this issue right now.
I've no clue why I miss it during implementation :-/

**Comment by ger-benjamin** [comment]
@jansule @sebastianfrey, Do we have a case where we should keep the comma separation notation ? I've seen only doc about value separated by spaces, and not comma.

**Comment by sebastianfrey** [comment]
@ger-benjamin The question is: How did you come up with it? Did you find some sample SLD, which did use comma separated values? Or was it just by mistake?

**Comment by sebastianfrey** [comment]
Ok, digged down the rabbit hole: GeoServer uses Geotools for SLD handling and Geotools only supports spaces for `graphic-margin`: 

https://github.com/geotools/geotools/blob/main/modules/library/render/src/main/java/org/geotools/renderer/VendorOptionParser.java#L102

So it should be safe, remove the comma separated notation.

**Comment by ger-benjamin** [comment]
I work with an older and new parser system. And the old one also added graphic-margin **without** comma. That's not a version problem or so.
I'm copying the resulting style to ensure GeoServer understand it. Therefor I don't understand how it's possible that I've added commas. That could be a "last minutes" mistake by doing the tests.

Can I open a PR right now to remove the comma support ? And again, sorry, for that...

**Comment by jansule** [comment]
No worries @ger-benjamin, things like these happen. And thanks for catching the missing part in #989. I shouldn't do code reviews in the mornings :smile:
