### PR TITLE
fix: Test if opacity is realy undefined

### LINKED ISSUE #967: Some values are considered as undefined but are 0
# Bug

**Describe the bug**

If the (fill/stroke/)opacity is 0, in some cases the parser don't handle it.
The resulting sld doesn't contain any Opacity value, but should contains one with value set 0.

**To Reproduce**
 - Take a MarkSymbolizer with opacity 0.
 - Transform it
 - Use the generated sld in Geoserver (for instance)

The opacity will be not set and that can cause styling issues.

**Expected behavior**
The sld contains an `Opacity` property with value to 0.

### PR DESCRIPTION
**Pull request by ger-benjamin**
Fix #967 

Test if opacity value is undefined or null, but not 0.

### CODE REVIEW

File: src/SldStyleParser.ts [hunk 1]
```diff
@@ -808,7 +812,7 @@ export class SldStyleParser implements StyleParser<string> {
     }
 
     textSymbolizer.color = color ? color : '#000000';
-    textSymbolizer.opacity = opacity ? numberExpression(opacity) : 1;
+    textSymbolizer.opacity = isNil(opacity) ? 1 : numberExpression(opacity);
```
Comment (jansule) [inline src/SldStyleParser.ts:815]: I'm not sure if we should set the opacity at all, if it is not set in the given style, so the default of the used renderer applies. @KaiVolland what do you think?

**Review by jansule — COMMENTED** [review]
Very nice! Thanks @ger-benjamin. Just a small remark we might want to address first.

File: src/SldStyleParser.ts (hunk 1 above)
Comment (KaiVolland) [reply src/SldStyleParser.ts:815]: :+1: Forcing an opacity value on the geostyler-style is actually not needed.

Comment (ger-benjamin) [reply src/SldStyleParser.ts:815]: Ok, so, I'll remove the ternary operator, and only assign the opacity if the parameter is provided

Comment (jansule) [reply src/SldStyleParser.ts]: Sounds good to me. Please note that this results in a breaking change (which is totally fine). So it would be great, if you could add the information into the commit message.

**Comment by ger-benjamin** [comment]
More changes than expected, but I think is all right.
I let you merge if it looks correct to you @jansule

**Review by KaiVolland — APPROVED** [review]
